// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    author: "Gayle Laakmann McDowell",
    url: "https://m.media-amazon.com/images/I/61mIq2iJUXL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
    summary1: "I am not a recruiter. I am a software engineer. And as such, I know what it's like to be asked to whip up brilliant algorithms on the spot and then write flawless code on a whiteboard. I've been through this as a candidate and as an interviewer.",
    summary2: "Cracking the Coding Interview, 6th Edition is here to help you through this process, teaching you what you need to know and enabling you to perform at your very best. I've coached and interviewed hundreds of software engineers. The result is this book.",
    summary3: "Learn how to uncover the hints and hidden details in a question, discover how to break down a problem into manageable chunks, develop techniques to unstick yourself when stuck, learn (or re-learn) core computer science concepts, and practice on 189 interview questions and solutions.",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    url: "https://m.media-amazon.com/images/I/81ANaVZk5LL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
    summary1: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    summary2: "If you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change. You do not rise to the level of your goals. You fall to the level of your systems. Here, you'll get a proven system that can take you to new heights.",
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    author: "David Goggins",
    url: "https://m.media-amazon.com/images/I/81gTRv2HXrL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    summary1: "For David Goggins, childhood was a nightmare -- poverty, prejudice, and physical abuse colored his days and haunted his nights. But through self-discipline, mental toughness, and hard work, Goggins transformed himself from a depressed, overweight young man with no future into a U.S. Armed Forces icon and one of the world's top endurance athletes. The only man in history to complete elite training as a Navy SEAL, Army Ranger, and Air Force Tactical Air Controller, he went on to set records in numerous endurance events.",
    summary2: "In Can't Hurt Me, he shares his astonishing life story and reveals that most of us tap into only 40% of our capabilities. Goggins calls this The 40% Rule, and his story illuminates a path that anyone can follow to push past pain, demolish fear, and reach their full potential.",
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    url: "https://m.media-amazon.com/images/I/91nujEwIpYL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
    summary1: "Deep work is the ability to focus without distraction on a cognitively demanding task. It's a skill that allows you to quickly master complicated information and produce better results in less time. Deep Work will make you better at what you do and provide the sense of true fulfillment that comes from craftsmanship.",
    summary2: "In short, deep work is like a super power in our increasingly competitive twenty-first century economy. And yet, most people have lost the ability to go deep-spending their days instead in a frantic blur of e-mail and social media, not even realizing there's a better way.",
  },
  {
    id: 5,
    title: "The 10X Rule",
    author: "Grant Cardone",
    url: "https://m.media-amazon.com/images/I/71hjq42hvGL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
    summary1: "While most people operate with only three degrees of action-no action, retreat, or normal action-if you're after big goals, you don't want to settle for the ordinary. To reach the next level, you must understand the coveted 4th degree of action. This 4th degree, also known as the 10 X Rule, is that level of action that guarantees companies and individuals realize their goals and dreams.",
    summary2: "Extreme success is by definition outside the realm of normal action. Instead of behaving like everybody else and settling for average results, take Massive Action with The 10 X Rule, remove luck and chance from your business equation, and lock in massive success.",
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    author: "Grant Cardone",
    url: "https://m.media-amazon.com/images/I/616OvChM3RL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
    summary1: "Whether it's selling your company's product in the boardroom or selling yourself on eating healthy, everything in life can and should be treated as a sale. And as sales expert Grant Cardone explains, knowing the principles of selling is a prerequisite for success of any kind.",
    summary2: "Cardone breaks down the techniques and approaches necessary to master the art of selling in any avenue. You will learn how to handle rejection, turn around negative situations, shorten sales cycles, and guarantee yourself greatness.",
    summary3: "With the experience of a seasoned sales vet at the helm, Sell or Be Sold will change the way you perceive the sale and life.",
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    url: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
    summary1: "Robert's story of growing up with two dads - his real father and the father of his best friend, his rich dad - and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
    summary2: "In the 20th anniversary edition of this classic, Robert offers an update on what we’ve seen over the past 20 years related to money, investing, and the global economy. Sidebars throughout the book will take readers “fast forward” - from 1997 to today - as Robert assesses how the principles taught by his rich dad have stood the test of time.",
    summary3: "In many ways, the messages of Rich Dad Poor Dad, messages that were criticized and challenged two decades ago, are more meaningful, relevant and important today than they were 20 years ago.",
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    author: "Robert T. Kiyosaki",
    url: "https://m.media-amazon.com/images/I/71+SWQ6xj1L._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
    summary1: "CASHFLOW Quadrant was written for those who are ready to move beyond job security and enter the world of financial freedom. It’s for those who want to make significant changes in their lives and take control of their financial future.",
    summary2: "Robert believes that the reason most people struggle financially is because they've spent years in school but were never taught about money. Robert’s rich dad taught him that this lack of financial education is why so many people work so hard all their lives for money...instead of learning how to make money work for them.",
    summary3: "This book will change the way you think about jobs, careers, and owning your own business and inspire you to learn the rules of money that the rich use to build and grow their wealth.",
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    author: "Robert Greene",
    url: "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
    summary1: "Robert Greene and Joost Elffers have distilled three thousand years of the history of power into 48 essential laws by drawing from the philosophies of Machiavelli, Sun Tzu, and Carl Von Clausewitz and also from the lives of figures ranging from Henry Kissinger to P.T. Barnum.",
    summary2: "Some laws teach the need for prudence (“Law 1: Never Outshine the Master”), others teach the value of confidence (“Law 28: Enter Action with Boldness”), and many recommend absolute self-preservation (“Law 15: Crush Your Enemy Totally”). Every law, though, has one thing in common: an interest in total domination. In a bold and arresting two-color package, The 48 Laws of Power is ideal whether your aim is conquest, self-defense, or simply to understand the rules of the game.",
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    author: "Mel Robbins",
    url: "https://m.media-amazon.com/images/I/91wOERyhh7L._UF1000,1000_QL80_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
    summary1: "The 5 Second Rule is the secret to changing anything about your life. You can use the Rule and its countdown method to break any bad habit, interrupt self-doubt and negative self-talk, and push yourself to take the actions that will change your life.",
    summary2: "Using the science of habits, riveting stories, and surprising facts from some of the most famous moments in history, Mel Robbins will explain the power of a five second decision. You'll also meet and inspired by hundreds of people around the world who are using the Rule to achieve their goals, reach their potential, and chase their dreams.",
    summary3: "In the book, you'll learn the inspiring and relatable story of how Mel invented the 5 Second Rule during the worst moment of her life, when her anxiety and finances were so bad, she could barely get out of bed. Since creating the Rule, Mel has shared it with audiences around the world, the most respected brands, and people who want to make real and lasting change.",
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    url: "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
    summary1: "Dale Carnegie’s rock-solid, time-tested advice has carried countless people up the ladder of success in their business and personal lives. One of the most groundbreaking and timeless bestsellers of all time, How to Win Friends & Influence People will teach you:",
    summary2: "Six ways to make people like you. Twelve ways to win people to your way of thinking. Nine ways to change people without arousing resentment.",
    summary3: "And much more! Achieve your maximum potential—a must-read for the twenty-first century with more than 15 million copies sold!",
  },
  {
    id: 12,
    title: "Mastery",
    author: "Robert Greene",
    url: "https://m.media-amazon.com/images/I/51V3121nmkL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
    summary1: "In this book, Robert Greene demonstrates that the ultimate form of power is mastery itself.",
    summary2: "By analyzing the lives of such past masters as Charles Darwin, Benjamin Franklin, Albert Einstein, and Leonard da Vinci, as well as by interviewing nine contemporary masters, including tech guru Paul Graham and animal rights advocate Temple Grandin, Greene debunks our culture’s many myths about genius and distills the wisdom of the ages to reveal the secret to greatness. With this seminal text as a guide, readers will learn how to unlock the passion within and become masters.",
  },
];